version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
      - "22"

  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
      - 3773:3773
      - 3772:3772

  supervisor:
    image: storm
    volumes:
      - ./storm/examples/storm-starter/target:/storm/examples/storm-starter/target
    container_name: supervisor
    command: "storm supervisor"
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
    ports:
      - 8000
      - 22


  ui:
    image: storm
    command: storm ui
    ports:
      - "8080:8080"
      - "22"
    links:
      - nimbus
    external_links